version: "3.3"
services:
  scraper:
    container_name: ratings_scraper
    build: ./scraper
    volumes:
      - csv_path:/var/csv_path/
  web-app:
    container_name: ratings_web_app
    build: ./web-app
    volumes:
      - csv_path:/var/csv_path/
    ports:
      - "80:8080"
  uploader:
    container_name: dataworld_uploader
    build: ./data.world_upload/
    volumes:
      - csv_path:/var/csv_path/


volumes:
     csv_path: